### ISSUE TITLE
老哥，你跑通shayneobrien/coreference-resolution了么？

### ISSUE THREAD

**Issue by RichardHWD** [zxy951005/Paper-Reading-Notes#1]
老哥，我有看到你在9月的时候在shayneobrien/coreference-resolution留言你无法收敛，我最近也在初学消解，不太会TensorFlow，我用coreference-resolution的代码跑到一半就各种BUG报错（数据和embedding没问题），请问你跑通shayneobrien/coreference-resolution了么？能否分享一下

**Comment by RichardHWD** [comment]
在线等

**Comment by zxy951005** [comment]
跑通了，但是没收敛






在 2019-12-30 09:00:19，"RichardHWD" <notifications@github.com> 写道：

Closed #1.
